version: '3.9'

# services:
#   database:
#     image: 'postgres:alpine'
#     ports:
#       - 5432:5432
#     networks:
#       - postgres-network
#     env_file:
#       - .env
#     volumes:
#       - postgres:/var/lib/postgresql/data/
  
#   pgadmin:
#     image: dpage/pgadmin4
#     ports:
#       - 5050:80
#     env_file:
#       - .env
#     depends_on:
#       - database
#     networks:
#       - postgres-network
#     volumes:
#       - pgadmin:/var/lib/pgadmin/

# networks: 
#   postgres-network:
#     driver: bridge
services:
  #mongo server
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27016:27017


volumes:
  mongo_db: {}
  postgres: {}
  pgadmin: {}